### ISSUE TITLE
Add An English transcript readme.md file

### ISSUE THREAD

**Issue by jitendra3109** [marktony/Awesome_API#23]
I'm just across the repo for seeing Awesome APIs but unfortunity I could not understand anythin what do you written coz of I don't know the chinese.
Please add english script so it will help for more open source users.

**Comment by TonnyL** [comment]
Sorry for that. But in fact, most APIs that written by Chinese are collected in the global part too. The other you can not find may be not available outside of China. Anyway, I will translate all the content to English soon. Happy coding 😀!

BTW, though the readme file is divided into two parts,  the content is same.

**Comment by jitendra3109** [comment]
Thank for considering.
Good job. :1st_place_medal: 
You do have also global part too.
Please mentions there near Global Part of it is also in English and Also in the top most and font size should  h1.
I appreciate your work.
I do have to close this issue because you have already English transcript.
