### ISSUE TITLE
English version points to 404

### ISSUE THREAD

**Issue by ayush000** [marktony/Awesome_API#3]
![screen shot 2017-01-20 at 5 01 27 pm](https://cloud.githubusercontent.com/assets/1942688/22148327/7553c9c2-df33-11e6-9f4b-b5e218bfaf84.png)

Clicking on this gives 404

**Comment by TonnyL** [comment]
Yes, it is a bug when I merge the pull request. I fixed it just now. Hope it's helpful.  @ayush000
